-- Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2021.2 (lin64) Build 3367213 Tue Oct 19 02:47:39 MDT 2021
-- Date        : Sun Oct 13 13:42:14 2024
-- Host        : lywong-thin running 64-bit unknown
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_vivado_cache_wrapper_0_0_sim_netlist.vhdl
-- Design      : design_1_vivado_cache_wrapper_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xcu280-fsvh2892-2L-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    clk : in STD_LOGIC;
    rst_n : in STD_LOGIC;
    axil_awaddr_sbd : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_awvalid_sbd : in STD_LOGIC;
    axil_awready_sbd : out STD_LOGIC;
    axil_wdata_sbd : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_wvalid_sbd : in STD_LOGIC;
    axil_wready_sbd : out STD_LOGIC;
    axil_bresp_sbd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axil_bvalid_sbd : out STD_LOGIC;
    axil_bready_sbd : in STD_LOGIC;
    axil_araddr_sbd : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_arvalid_sbd : in STD_LOGIC;
    axil_arready_sbd : out STD_LOGIC;
    axil_rdata_sbd : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_rvalid_sbd : out STD_LOGIC;
    axil_rresp_sbd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axil_rready_sbd : in STD_LOGIC;
    axil_awaddr_mng : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_awvalid_mng : out STD_LOGIC;
    axil_awready_mng : in STD_LOGIC;
    axil_wdata_mng : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_wvalid_mng : out STD_LOGIC;
    axil_wready_mng : in STD_LOGIC;
    axil_bresp_mng : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axil_bvalid_mng : in STD_LOGIC;
    axil_bready_mng : out STD_LOGIC;
    axil_araddr_mng : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_arvalid_mng : out STD_LOGIC;
    axil_arready_mng : in STD_LOGIC;
    axil_rdata_mng : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axil_rresp_mng : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axil_rvalid_mng : in STD_LOGIC;
    axil_rready_mng : out STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_vivado_cache_wrapper_0_0,vivado_cache_wrapper,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "module_ref";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "vivado_cache_wrapper,Vivado 2021.2";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \<const0>\ : STD_LOGIC;
  signal \<const1>\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of axil_arready_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng ARREADY";
  attribute X_INTERFACE_INFO of axil_arready_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd ARREADY";
  attribute X_INTERFACE_INFO of axil_arvalid_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng ARVALID";
  attribute X_INTERFACE_INFO of axil_arvalid_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd ARVALID";
  attribute X_INTERFACE_INFO of axil_awready_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng AWREADY";
  attribute X_INTERFACE_INFO of axil_awready_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd AWREADY";
  attribute X_INTERFACE_INFO of axil_awvalid_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng AWVALID";
  attribute X_INTERFACE_INFO of axil_awvalid_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd AWVALID";
  attribute X_INTERFACE_INFO of axil_bready_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng BREADY";
  attribute X_INTERFACE_INFO of axil_bready_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd BREADY";
  attribute X_INTERFACE_INFO of axil_bvalid_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng BVALID";
  attribute X_INTERFACE_INFO of axil_bvalid_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd BVALID";
  attribute X_INTERFACE_INFO of axil_rready_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng RREADY";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of axil_rready_mng : signal is "XIL_INTERFACENAME axil_mng, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_CLK, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axil_rready_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd RREADY";
  attribute X_INTERFACE_PARAMETER of axil_rready_sbd : signal is "XIL_INTERFACENAME axil_sbd, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_CLK, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axil_rvalid_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng RVALID";
  attribute X_INTERFACE_INFO of axil_rvalid_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd RVALID";
  attribute X_INTERFACE_INFO of axil_wready_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng WREADY";
  attribute X_INTERFACE_INFO of axil_wready_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd WREADY";
  attribute X_INTERFACE_INFO of axil_wvalid_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng WVALID";
  attribute X_INTERFACE_INFO of axil_wvalid_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd WVALID";
  attribute X_INTERFACE_INFO of clk : signal is "xilinx.com:signal:clock:1.0 clk CLK";
  attribute X_INTERFACE_PARAMETER of clk : signal is "XIL_INTERFACENAME clk, ASSOCIATED_BUSIF axil_mng:axil_sbd, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_CLK, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst_n : signal is "xilinx.com:signal:reset:1.0 rst_n RST";
  attribute X_INTERFACE_PARAMETER of rst_n : signal is "XIL_INTERFACENAME rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axil_araddr_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng ARADDR";
  attribute X_INTERFACE_INFO of axil_araddr_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd ARADDR";
  attribute X_INTERFACE_INFO of axil_awaddr_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng AWADDR";
  attribute X_INTERFACE_INFO of axil_awaddr_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd AWADDR";
  attribute X_INTERFACE_INFO of axil_bresp_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng BRESP";
  attribute X_INTERFACE_INFO of axil_bresp_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd BRESP";
  attribute X_INTERFACE_INFO of axil_rdata_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng RDATA";
  attribute X_INTERFACE_INFO of axil_rdata_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd RDATA";
  attribute X_INTERFACE_INFO of axil_rresp_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng RRESP";
  attribute X_INTERFACE_INFO of axil_rresp_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd RRESP";
  attribute X_INTERFACE_INFO of axil_wdata_mng : signal is "xilinx.com:interface:aximm:1.0 axil_mng WDATA";
  attribute X_INTERFACE_INFO of axil_wdata_sbd : signal is "xilinx.com:interface:aximm:1.0 axil_sbd WDATA";
begin
  axil_araddr_mng(31) <= \<const0>\;
  axil_araddr_mng(30) <= \<const0>\;
  axil_araddr_mng(29) <= \<const0>\;
  axil_araddr_mng(28) <= \<const0>\;
  axil_araddr_mng(27) <= \<const0>\;
  axil_araddr_mng(26) <= \<const0>\;
  axil_araddr_mng(25) <= \<const0>\;
  axil_araddr_mng(24) <= \<const0>\;
  axil_araddr_mng(23) <= \<const0>\;
  axil_araddr_mng(22) <= \<const0>\;
  axil_araddr_mng(21) <= \<const0>\;
  axil_araddr_mng(20) <= \<const0>\;
  axil_araddr_mng(19) <= \<const0>\;
  axil_araddr_mng(18) <= \<const0>\;
  axil_araddr_mng(17) <= \<const0>\;
  axil_araddr_mng(16) <= \<const0>\;
  axil_araddr_mng(15) <= \<const0>\;
  axil_araddr_mng(14) <= \<const0>\;
  axil_araddr_mng(13) <= \<const0>\;
  axil_araddr_mng(12) <= \<const0>\;
  axil_araddr_mng(11) <= \<const0>\;
  axil_araddr_mng(10) <= \<const0>\;
  axil_araddr_mng(9) <= \<const0>\;
  axil_araddr_mng(8) <= \<const0>\;
  axil_araddr_mng(7) <= \<const0>\;
  axil_araddr_mng(6) <= \<const0>\;
  axil_araddr_mng(5) <= \<const0>\;
  axil_araddr_mng(4) <= \<const0>\;
  axil_araddr_mng(3) <= \<const0>\;
  axil_araddr_mng(2) <= \<const0>\;
  axil_araddr_mng(1) <= \<const0>\;
  axil_araddr_mng(0) <= \<const0>\;
  axil_arready_sbd <= \<const1>\;
  axil_arvalid_mng <= \<const0>\;
  axil_awaddr_mng(31) <= \<const0>\;
  axil_awaddr_mng(30) <= \<const0>\;
  axil_awaddr_mng(29) <= \<const0>\;
  axil_awaddr_mng(28) <= \<const0>\;
  axil_awaddr_mng(27) <= \<const0>\;
  axil_awaddr_mng(26) <= \<const0>\;
  axil_awaddr_mng(25) <= \<const0>\;
  axil_awaddr_mng(24) <= \<const0>\;
  axil_awaddr_mng(23) <= \<const0>\;
  axil_awaddr_mng(22) <= \<const0>\;
  axil_awaddr_mng(21) <= \<const0>\;
  axil_awaddr_mng(20) <= \<const0>\;
  axil_awaddr_mng(19) <= \<const0>\;
  axil_awaddr_mng(18) <= \<const0>\;
  axil_awaddr_mng(17) <= \<const0>\;
  axil_awaddr_mng(16) <= \<const0>\;
  axil_awaddr_mng(15) <= \<const0>\;
  axil_awaddr_mng(14) <= \<const0>\;
  axil_awaddr_mng(13) <= \<const0>\;
  axil_awaddr_mng(12) <= \<const0>\;
  axil_awaddr_mng(11) <= \<const0>\;
  axil_awaddr_mng(10) <= \<const0>\;
  axil_awaddr_mng(9) <= \<const0>\;
  axil_awaddr_mng(8) <= \<const0>\;
  axil_awaddr_mng(7) <= \<const0>\;
  axil_awaddr_mng(6) <= \<const0>\;
  axil_awaddr_mng(5) <= \<const0>\;
  axil_awaddr_mng(4) <= \<const0>\;
  axil_awaddr_mng(3) <= \<const0>\;
  axil_awaddr_mng(2) <= \<const0>\;
  axil_awaddr_mng(1) <= \<const0>\;
  axil_awaddr_mng(0) <= \<const0>\;
  axil_awready_sbd <= \<const1>\;
  axil_awvalid_mng <= \<const0>\;
  axil_bready_mng <= \<const0>\;
  axil_bresp_sbd(1) <= \<const0>\;
  axil_bresp_sbd(0) <= \<const0>\;
  axil_bvalid_sbd <= \<const0>\;
  axil_rdata_sbd(31) <= \<const0>\;
  axil_rdata_sbd(30) <= \<const0>\;
  axil_rdata_sbd(29) <= \<const0>\;
  axil_rdata_sbd(28) <= \<const0>\;
  axil_rdata_sbd(27) <= \<const0>\;
  axil_rdata_sbd(26) <= \<const0>\;
  axil_rdata_sbd(25) <= \<const0>\;
  axil_rdata_sbd(24) <= \<const0>\;
  axil_rdata_sbd(23) <= \<const0>\;
  axil_rdata_sbd(22) <= \<const0>\;
  axil_rdata_sbd(21) <= \<const0>\;
  axil_rdata_sbd(20) <= \<const0>\;
  axil_rdata_sbd(19) <= \<const0>\;
  axil_rdata_sbd(18) <= \<const0>\;
  axil_rdata_sbd(17) <= \<const0>\;
  axil_rdata_sbd(16) <= \<const0>\;
  axil_rdata_sbd(15) <= \<const0>\;
  axil_rdata_sbd(14) <= \<const0>\;
  axil_rdata_sbd(13) <= \<const0>\;
  axil_rdata_sbd(12) <= \<const0>\;
  axil_rdata_sbd(11) <= \<const0>\;
  axil_rdata_sbd(10) <= \<const0>\;
  axil_rdata_sbd(9) <= \<const0>\;
  axil_rdata_sbd(8) <= \<const0>\;
  axil_rdata_sbd(7) <= \<const0>\;
  axil_rdata_sbd(6) <= \<const0>\;
  axil_rdata_sbd(5) <= \<const0>\;
  axil_rdata_sbd(4) <= \<const0>\;
  axil_rdata_sbd(3) <= \<const0>\;
  axil_rdata_sbd(2) <= \<const0>\;
  axil_rdata_sbd(1) <= \<const0>\;
  axil_rdata_sbd(0) <= \<const0>\;
  axil_rready_mng <= \<const0>\;
  axil_rresp_sbd(1) <= \<const0>\;
  axil_rresp_sbd(0) <= \<const0>\;
  axil_rvalid_sbd <= \<const0>\;
  axil_wdata_mng(31) <= \<const0>\;
  axil_wdata_mng(30) <= \<const0>\;
  axil_wdata_mng(29) <= \<const0>\;
  axil_wdata_mng(28) <= \<const0>\;
  axil_wdata_mng(27) <= \<const0>\;
  axil_wdata_mng(26) <= \<const0>\;
  axil_wdata_mng(25) <= \<const0>\;
  axil_wdata_mng(24) <= \<const0>\;
  axil_wdata_mng(23) <= \<const0>\;
  axil_wdata_mng(22) <= \<const0>\;
  axil_wdata_mng(21) <= \<const0>\;
  axil_wdata_mng(20) <= \<const0>\;
  axil_wdata_mng(19) <= \<const0>\;
  axil_wdata_mng(18) <= \<const0>\;
  axil_wdata_mng(17) <= \<const0>\;
  axil_wdata_mng(16) <= \<const0>\;
  axil_wdata_mng(15) <= \<const0>\;
  axil_wdata_mng(14) <= \<const0>\;
  axil_wdata_mng(13) <= \<const0>\;
  axil_wdata_mng(12) <= \<const0>\;
  axil_wdata_mng(11) <= \<const0>\;
  axil_wdata_mng(10) <= \<const0>\;
  axil_wdata_mng(9) <= \<const0>\;
  axil_wdata_mng(8) <= \<const0>\;
  axil_wdata_mng(7) <= \<const0>\;
  axil_wdata_mng(6) <= \<const0>\;
  axil_wdata_mng(5) <= \<const0>\;
  axil_wdata_mng(4) <= \<const0>\;
  axil_wdata_mng(3) <= \<const0>\;
  axil_wdata_mng(2) <= \<const0>\;
  axil_wdata_mng(1) <= \<const0>\;
  axil_wdata_mng(0) <= \<const0>\;
  axil_wready_sbd <= \<const1>\;
  axil_wvalid_mng <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
VCC: unisim.vcomponents.VCC
     port map (
      P => \<const1>\
    );
end STRUCTURE;
