#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 17 13:23:12 EDT 2024
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim AXI_GPIO_tb_behav -key {Behavioral:sim_1:Functional:AXI_GPIO_tb} -tclbatch AXI_GPIO_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/share/home/bashista/CIS5710_Cache_Template/vivado_proj/cache_test/AXI_GPIO_tb_behav.wcfg -log simulate.log"
xsim AXI_GPIO_tb_behav -key {Behavioral:sim_1:Functional:AXI_GPIO_tb} -tclbatch AXI_GPIO_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /mnt/share/home/bashista/CIS5710_Cache_Template/vivado_proj/cache_test/AXI_GPIO_tb_behav.wcfg -log simulate.log

